services:
  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: logistack-backend
    ports:
      - "5000:3000"         # Expose NestJS on localhost:5000
    env_file:
      - ../.env
    depends_on:
      - db

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    container_name: logistack-frontend
    ports:
      - "3000:3000"         # Next.js on localhost:3000
    env_file:
      - ../.env
    depends_on:
      - backend
    volumes:
      - ../apps/frontend:/app

  db:
    image: postgres:15
    container_name: logistack-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logistack
    volumes:
      - postgres_data:/var/lib/postgresql/data

  logistack-platform:
    build:
      context: ../services
      dockerfile: Dockerfile
    container_name: logistack-platform
    ports:
    - "8000:8000"
    env_file:
    - ../.env
    depends_on:
    - db


  nginx:
    image: nginx:latest
    container_name: logistack-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
