services:
  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    container_name: logistack-backend
    ports:
      - "5000:3000"         # Expose NestJS on localhost:5000
    env_file:
      - ../.env
    depends_on:
      - db

  frontend:
    build:
      context: ../apps/frontend/frontend-client
      dockerfile: Dockerfile
    container_name: logistack-frontend
    ports:
      - "3000:3000"         # Next.js on localhost:3000
    env_file:
      - ../.env
    depends_on:
      - backend
    volumes:
      - ../apps/frontend/frontend-client:/app
    
  frontend-driver:
    build:
      context: ../apps/frontend/frontend-driver
      dockerfile: Dockerfile
    container_name: logistack-frontend-driver
    ports:
      - "4000:3000"         # Next.js on localhost:4000
    env_file:
      - ../.env
    depends_on:
      - backend
    volumes:
      - ../apps/frontend/frontend-driver:/app

  db:
    image: postgres:15
    container_name: logistack-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logistack
    volumes:
      - postgres_data:/var/lib/postgresql/data

  logistack-platform:
    build:
      context: ../services
      dockerfile: Dockerfile
    container_name: logistack-platform
    ports:
    - "8000:8000"
    env_file:
    - ../.env
    depends_on:
    - db


  nginx:
    image: nginx:latest
    container_name: logistack-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

volumes:
  postgres_data:
